### ISSUE TITLE
Specific SSML tags are not working.

### ISSUE THREAD

**Issue by ShaliniKrishnamoorthy** [gsdriver/ssml-check#13]
**Describe the bug**
Specific SSML tags are not working like amazon:domain, amazon:breath.
eg: 
<speak><amazon:domain name=""conversational"">Hi! Hello World</amazon:domain></speak>
<speak><amazon:breath duration="medium" volume="x-loud"/> Agents are <say-as interpret-as="characters">assisting</say-as> other callers</speak>

1. Since we are not using locale id in our scenario, its always entering into the if condition of locale id in amazon domain function.
2. In ssml-check-core/index.js, we have an if constraint for creating an element.name. But this condition is failing for amazon:domain and amazon:breath tag due to not condition. ( **!**(((platform === 'amazon') && (validAmazonTags.indexOf(element.name) !== -1)))
we tried by removing that NOT condition, it worked. but it failed in above mentioned scenario 1. 

**To Reproduce**
<speak><amazon:domain name=""conversational"">Hi! Hello World</amazon:domain></speak>
<speak><amazon:breath duration="medium" volume="x-loud"/> Agents are <say-as interpret-as="characters">assisting</say-as> other callers</speak>

**Expected behavior**
1. Since we are not using locale id in our scenario, its always entering into the if condition of locale id in amazon domain function.
2. In ssml-check-core/index.js, we have an if constraint for creating an element.name. But this condition is failing for amazon:domain and amazon:breath tag due to not condition. ( **!**(((platform === 'amazon') && (validAmazonTags.indexOf(element.name) !== -1)))
we tried by removing that NOT condition, it worked. but it failed in above mentioned scenario 1. 

**Environment (please complete the following information):**
 - Platform: Amazon
 - Version 0.4.4(ssml-check)

**Additional context**

**Comment by gsdriver** [comment]
Confirmed from the Amazon SSML docs that locale should be optional for amazon:domain tag. I've made a change in ssml-check-core (version 0.3.7) and updated ssml-check to include this version of ssml-check-core (in version 0.4.5 of ssml-check). I also added these two examples into the test suite under test/test.js and verified that they are working properly.

As for the check of platform in ssml-check-core/index.js, that wasn't an issue for me. Check the calls in test/test.js and make sure you're setting the platform field in the options structure to "amazon" (note that it's case sensitive)
