### ISSUE TITLE
speed-Attribute validation appears to be wrong

### ISSUE THREAD

**Issue by janniksam** [gsdriver/ssml-check#4]
According to the google documentation the values are followed by "%", which isn't valid with the given regex:

**Documentation**:

> The ratio output playback rate relative to the normal input rate expressed as a percentage. The format is a positive Real Number followed by %. The currently supported range is [50% (slow - half speed), 200% (fast - double speed)]. Values outside that range may (or may not) be adjusted to be within it.

**Validation**:

```
} else if ((platform === 'google') && (attribute === 'speed')) {
              if (!element.attributes.speed.match(/^(\+)?[0-9]+(\.[0-9]+)?$/g)) {
                errors.push(createTagError(element, attribute));
}
```

Maybe try something like `^\\d+%` instead.

**Comment by janniksam** [comment]
Further more I'd rather use `^[+-]([0-9]|[1-3][0-9]|40)dB$` for the soundLevel, because Google limits it between -40dB and +40dB.

**Comment by gsdriver** [comment]
Good catches - I published version 0.2.2 with fixes:

- updated speed to check for the trailing %, and to make sure that the value is between 50 and 200. 
- For soundLevel, I also make sure the value is between -40 and +40. I can't exactly use the regEx you noted since this is a real number (need to account for decimals).

**Comment by janniksam** [comment]
Oh, my bad, I didn't see, they allow decimals. This might work better, so you don't need to extra parse it:
Please be aware, I have restricted it to 2 decimal places...

`^[+-](([0-9]?(.\d{0,2}))|([1-3][0-9]?(.\d{0,2}))|40)dB$`

**Comment by janniksam** [comment]
Oops. My bad. I didn't read, they allow decimal places.

Here is an updated RegEx. Please take note, I limited the decimal places to two places max:
`^[+-](([0-9](\.\d{1,2})?)|([1-3][0-9](\.\d{1,2})?)|40)dB$`

https://regex101.com/r/6S5SFj/1
