### ISSUE TITLE
Typescript declaration files

### ISSUE THREAD

**Issue by armonge** [gsdriver/ssml-check#9]
**Is your feature request related to a problem? Please describe.**
I've been using ssml-check with a couple typescript project and while it works great the fact that there's no declaration files means a couple of niceties about typescript like getting options autocompletion in IDE and stuff are lost

**Describe the solution you'd like**
I would like to contribute a typescript declaration file in the form of a an index.d.ts and a change in the package.json file to reference this types

**Describe alternatives you've considered**
Alternatively i could also publish a new package with the name @types/ssml-check to  http://definitelytyped.org/ but i believe it would be best to have the typescript declarations in the same package

**Additional context**
https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html
Example: dynamodb-local package
https://github.com/rynop/dynamodb-local/blob/master/package.json#L37
https://github.com/rynop/dynamodb-local/blob/master/index.d.ts

**Comment by gsdriver** [comment]
Sounds like a good addition to ssml-check - happy to take the contribution!
